name: Ferret
version: 0.0.1-PREALPHA
main: life.ferret.ferretPlugin.main
api-version: 1.19
author: BeanGirlThing
website: ferret.life
description: This plugin is a collection of tools or "Microplugins" to assist in various server scenarios.
softdepend:
  - Vault
  - NBTAPI

commands:
  allowedcommands:
    description: Shows a list of commands which operators can use without broadcasting into chat
    usage: /allowedcommands
    permission: FerretPlugin.AdminCommandBroadcaster.allowedcommands
    permission-message: You are not permitted to use this command

  stash:
    description: Allows an admin to store their inventory and current position while performing admin tasks
    usage: /stash
    permission: FerretPlugin.AdminToolbox.stash
    permission-message: You are not permitted to use this command

  unstash:
    description: Allows an admin to withdraw their stashed inventory and position returning to regular play
    usage: /unstash
    permission: FerretPlugin.AdminToolbox.unstash
    permission-message: You are not permitted to use this command

  deposit:
    description: Allows the user to deposit the specified amount of the currency item in exchange for Eco
    usage: /deposit [amount]
    permission: FerretPlugin.ItemEco.deposit
    permission-message: You are not permitted to use this command

  withdraw:
    description: Allows the user to withdraw the specified amount of Eco in exchange for the currency item
    usage: /withdraw [amount]
    permission: FerretPlugin.ItemEco.withdraw
    permission-message: You are not permitted to use this command


  ferret:
    description: Core plugin command to check status and modify the Ferret plugin.
    usage: | 
      /ferret (Shows the status of the plugin)
      /ferret reload (Reloads the features of the plugin)
      /ferret disable [feature] (Disables a specific feature of the plugin)
      /ferret enable [feature] (Enables a specific feature of the plugin)
    permission: FerretPlugin.core.ferret
    permission-message: You are not permitted to use this command
    aliases:
      - dook

  nethercoord:
    description: Shows equivalent nether coordinate for given overworld coordinates
    usage: /nethercoord [X] [Z]
    permission: FerretPlugin.PlayerToolbox.nethercoord
    permission-message: You are not permitted to use this command
  flex:
    description: Allows you to be an asshole
    usage: /flex
    permission: FerretPlugin.PlayerToolbox.flex
    permission-message: You are not permitted to use this command

permissions:
  FerretPlugin.operator:
    description: Unrestricted access to all Ferret plugin features
    children:
      FerretPlugin.admin: true
    default: op
  FerretPlugin.admin:
    description: Access to all 'Non Dangerous' administrator Ferret commands
    children:
      FerretPlugin.user: true
      FerretPlugin.AdminToolbox.stash: true
      FerretPlugin.AdminToolbox.unstash: true
      FerretPlugin.core.ferret: true
    default: false
  FerretPlugin.user:
    description: Non administrator access to Ferret commands
    children:
      FerretPlugin.AdminCommandBroadcaster.allowedcommands: true
      FerretPlugin.ItemEco.deposit: true
      FerretPlugin.ItemEco.withdraw: true
      FerretPlugin.PlayerToolbox.nethercoord: true
      FerretPlugin.PlayerToolbox.flex: true
    default: true
  FerretPlugin.BroadcastCommands:
    description: Broadcasts the commands of any user with this permission
    default: false


